name: release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: actions/setup-java@v2
        with:
          distribution: adopt-hotspot
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          gradle-version: 6.5.1

      - name: Run tests
        run: gradle check

      - name: Bump version
        id: version-bump
        uses: hennejg/github-tag-action@v4.1.jh1
        with:
          dry_run: true
          tag_prefix: ""
          default_bump: minor
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Assemble
        if: ${{ steps.version-bump.outputs.new_version }}
        run: gradle -Pversion=${{ steps.version-bump.outputs.new_version }} assemble

      - name: Create Github release
        uses: softprops/action-gh-release@v1
        id: create_github_release
        if: ${{ steps.version-bump.outputs.new_version }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          target_commitish: ${{ github.sha }}
          draft: false
          prerelease: false
          tag_name: "${{ steps.version-bump.outputs.new_version }}"
          name: "${{ steps.version-bump.outputs.new_version }}"
          files: |
            build/distributions/poi-to-discover-media-${{ steps.version-bump.outputs.new_version }}.zip
